[package]
name = "crabfetcher"
version = "0.1.3"
edition = "2021"
description = "A fetcher written in rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Eporax/crabfetcher"

[dependencies]
columns = "0.1.0"
sys-info = "0.9.1"
sysinfo = "0.26.4"
